/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern GoInt64 initVc(GoUint64 round);
extern GoInt64 prevDigestResetVc();
extern GoInt64 pushAddressDeltaVc(GoUint64 address, GoString deltaString, GoUint64 shard);
extern GoInt64 resetAddressDeltaVc(GoUint64 shard);
extern GoInt64 pushAddressCommitVc(GoUint64 address, GoUint64 shard);
extern GoInt64 resetAddressCommitVc(GoUint64 shard);
extern GoInt64 pushAddressBalanceVerifyVc(GoUint64 address, GoString balanceString, GoUint64 shard);
extern GoInt64 resetAddressBalanceVerifyVc(GoUint64 shard);

/* Return type for aggVc */
struct aggVc_return {
	char* r0;
	GoUint8 r1;
};
extern struct aggVc_return aggVc(GoUint64 nativeShard);
extern GoInt64 commitVc(GoUint64 nativeShard, GoUint64 round);
extern GoInt64 updateShardProofTreeVc(GoUint64 nativeShard);
extern GoUint8 verifyProofVc(GoString proofString, GoUint64 shard, GoUint64 round);
extern char* demoProof();
extern GoUint8 demoVerify(GoString proofString);

#ifdef __cplusplus
}
#endif
